{{- if .Values.global.keyVaultName }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: squad-secrets
  namespace: squad
  labels:
    {{- include "squad-agents.labels" . | nindent 4 }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ .Values.global.identityClientId | quote }}
    keyvaultName: {{ .Values.global.keyVaultName | quote }}
    tenantId: {{ .Values.global.tenantId | quote }}
    objects: |
      array:
        - |
          objectName: gh-token
          objectType: secret
          objectAlias: GH_TOKEN
{{- end }}
