apiVersion: v1
kind: Service
metadata:
  name: squad-coordinator
  namespace: squad
  labels:
    app.kubernetes.io/name: coordinator
    app.kubernetes.io/part-of: squad
    app.kubernetes.io/component: coordinator
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: coordinator
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
