apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: squad-keyvault-sync
  namespace: squad
  labels:
    app.kubernetes.io/part-of: squad
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "<your-msi-client-id>"
    keyvaultName: "<your-keyvault-name>"
    tenantId: "<your-tenant-id>"
    objects: |
      array:
        - |
          objectName: gh-token
          objectType: secret
        - |
          objectName: dk8s-autobot-password
          objectType: secret
  secretObjects:
    - secretName: squad-kv-secrets
      type: Opaque
      data:
        - objectName: gh-token
          key: gh-token
        - objectName: dk8s-autobot-password
          key: dk8s-autobot-password
